<?php
/**
 * Admin login credentials.
 *
 * DO NOT put a plain-text password here. ADMIN_PASSWORD_HASH must be
 * a bcrypt hash, generated by generate-password-hash.php (see below).
 *
 * Setup:
 *   1. Open admin/generate-password-hash.php in your browser once.
 *   2. Type the password you want, submit, copy the hash it shows you.
 *   3. Paste that hash below, replacing the placeholder.
 *   4. Delete generate-password-hash.php from the server — it's a
 *      one-time setup tool and shouldn't stay on a live site.
 */

define('ADMIN_USERNAME', 'admin');
define('ADMIN_PASSWORD_HASH', '$2y$10$jDF68mk0/gjPofdUkueR6uVIaQ.Mcg9ptLtbDExQHrMbg5G5tH/WS');
